export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ width: "100%", height: "100%" }}>
      <body
        style={{
          margin: 0,
          padding: 0,
          width: "100%",
          minHeight: "100dvh",
          overflow: "hidden",
          background: "#000",
        }}
      >
        {children}
      </body>
    </html>
  )
}
